name: 'sports_app_server'

services:
  nginx:
    container_name: nginx
    depends_on:
      - nest
    image: nginx:latest
    ports:
      - '4000:80'
    volumes:
      - ./tmp/files:/var/files
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped
    networks:
      - network

  nest:
    tty: true
    deploy:
      replicas: 2
    build:
      context: ../
      dockerfile: ./Dockerfile
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - ./tmp/files:/var/files
      - ./tmp/logs:/var/logs
    depends_on:
      - postgres
      - redis
    networks:
      - network

  redis:
    container_name: redis
    restart: unless-stopped
    image: redis:7.2
    ports:
      - "6379:6379"
    volumes:
      - ./tmp/redis-data:/data
    deploy:
      resources:
        limits:
          cpus: '0.05'
          memory: 300M
        reservations:
          cpus: '0.02'
          memory: 256M
    networks:
      - network

  postgres:
    container_name: postgres
    image: postgres:16
    ports:
      - "5432:5432"
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - ./tmp/db-data:/var/lib/postgresql/data
    networks:
      - network

volumes:
  tmp:

networks:
  network:
