version: '3.9'
name: 'sports_app'

services:
  gateway:
    container_name: sports_app_nest
    image: nest-api
    build:
      context: ../
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
#    volumes:
#      - .:/app
    environment:
      REDIS_HOST: redis
      UPLOAD_DIR: /var/files
    restart: unless-stopped
    volumes:
      - ./tmp/files:/var/files
      - ./tmp/logs:/var/logs
    depends_on:
      - postgres
      - redis
  redis:
    container_name: sports_app_redis
    restart: unless-stopped
    image: redis:7.2
    ports:
      - "6379:6379"
    volumes:
      - ./tmp/redis-data:/data

  postgres:
    container_name: sports_app_postgres
    image: postgres:16
    ports:
      - "5432:5432"
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - ./tmp/db-data:/data/postgres

  uploads:

    container_name: sports_app_uploads
    restart: unless-stopped
    image: nginx:1.25-alpine
    deploy:
      resources:
        limits:
          cpus: '0.01'
          memory: 128M
    ports:
      - 0.0.0.0:3001:80
    volumes:
      - ./uploads.nginx.conf:/etc/nginx/conf.d/default.conf
      - ./tmp/files:/var/files
